declare @fecha date=(convert(date,SYSDATETIME()))
--insert para las opciones de la oficina (menu opciones)
insert into opcionesOficina values(1, '001','Clientes')
insert into opcionesOficina values(2, '001','Compras')
insert into opcionesOficina values(3, '001','Contabilidad')
insert into opcionesOficina values(4, '001','Facturacion')
insert into opcionesOficina values(5, '001','Inventario')
insert into opcionesOficina values(6, '001','Usuarios')
insert into opcionesOficina values(7, '001','Ventas')
insert into opcionesOficina values(8, '002','Clientes')
insert into opcionesOficina values(9, '002','Compras')
insert into opcionesOficina values(10,'002','Contabilidad')
insert into opcionesOficina values(11,'002','Inventario')
insert into opcionesOficina values(12,'002','ServiciosPublicos')
insert into opcionesOficina values(13,'002','Usuarios')